import { useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
const Login = () => {
  const router = useRouter();

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log(email, password);
    console.log("submit");
    router.push("/home");
  };

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <div id="login" className="d-flex flex-column align-items-center">
      <Head>
        <title>Brup-Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="logo-container position-relative m-3 pointer"
        onClick={() => router.push("/")}
      >
        <Image
          src="/logo.png"
          alt="Logo"
          layout="responsive"
          width={7337}
          height={4920}
          priority={true}
        />
      </div>

      <div>
        <h3>Login your account</h3>
        <span>Fill in your credentials and start ordering</span>

        {/* email form */}
        <form className="my-5">
          <input
            type="email"
            placeholder="Email address"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="d-block w-100"
          />
          <input
            type="password"
            placeholder="Password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="d-block mt-4 w-100"
          />

          <button
            onClick={handleSubmit}
            className="btn d-block w-100 my-2 mt-4"
          >
            Login
          </button>
        </form>
        {/* email form */}

        <div className="d-flex flex-column align-items-center">
          <span>
            Don&apos;t have an account?&nbsp;
            <span
              className="text-primary pointer"
              onClick={() => router.push("/register")}
            >
              Register
            </span>
          </span>
          <span>
            Forgot your password?&nbsp;
            <span
              className="text-primary pointer"
              onClick={() => router.push("/forgot-password")}
            >
              Reset password
            </span>
          </span>

          <span>
            <span
              className="text-primary pointer"
              onClick={() => router.push("/")}
            >
              Back to Home
            </span>
          </span>
        </div>
      </div>
    </div>
  );
};

export default Login;
